CREATE TABLE SQUAD(
SQUAD_ID INT auto_increment,
SQUAD_NAME VARCHAR(20),
SLOT_ONE INT DEFAULT 0,
SLOT_TWO INT DEFAULT 0,
SLOT_THREE INT DEFAULT 0,
SLOT_FOUR INT DEFAULT 0,
SLOT_FIVE INT DEFAULT 0,
SLOT_SIX INT DEFAULT 0,
SQUAD_TRAINER_ID INT,
constraint SQUAD_ID_PK primary key (SQUAD_ID),
constraint FK_TRAINER_ID foreign key (SQUAD_TRAINER_ID)
)